Jian_pro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #
    url(r'', include('book.urls', namespace='book'))
]

book/urls.py
from django.conf.urls import url
from . import views as v

urlpatterns = [
    #首页
    url(r'^$', v.index, name='index'),
    #显示所有书目
    url(r'^books/$', v.books, name='books'),
    #显示特定书目
    url(r'^books/(?P<book_id>\d+)/$', v.book, name='book'),
    #显示特定的章节里面的讨论话题
    url(r'^chapter/(?P<chapter_id>\d+)/$', v.chapter, name='chapter'),
    #显示讨论话题的全部讨论内容
    url(r'^topic/(?P<topic_id>\d+)/$', v.topic, name='topic'),
    #添加新的讨论话题
    url(r'^new_topic/(?P<chapter_id>\d+)/$', v.new_topic, name='new_topic'),

]

book/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    '''python书目'''
    name = models.CharField(max_length=100)

    def __str__(self):
        '''返回字符串'''
        return self.name

class Chapter(models.Model):
    '''章'''
    name = models.CharField(max_length=50)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        '''返回'''
        return self.name

class Topic(models.Model):
    '''分享的观点或者问题'''
    topic = models.CharField(max_length=200)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    def __str__(self):
        '''返回'''
        return self.topic


class Entry(models.Model):
    '''关于某个主题的讨论'''
    entry = models.TextField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''返回前50个字'''
        return self.entry[:50] + '...'

book/forms.py
from django import forms
from .models import *

class TopicForm(forms.ModelForm):
    '''创建一个分享观点或问题的表单'''
    class Meta:
        model = Topic
        fields = ['topic']
        #不要为topic生成标签？
        labels = {'topic': ''}
        widgets = {'topic': forms.Textarea(attrs={'cols': 80,'rows': '10'})}

book/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect
#从核心-解析器导入反向解析
from django.core.urlresolvers import reverse
from .forms import TopicForm

# Create your views here.
def index(request):
    return render(request, 'book/index.html')

def books(request):
    '''显示所有书目'''
    books = Book.objects.order_by('id')
    context = {'books': books}
    return render(request, 'book/books.html', context)

def book(request, book_id):
    '''书的章节'''
    book = Book.objects.get(id=book_id)
    chapters = book.chapter_set.order_by('id')
    context = {'book': book, 'chapters': chapters}
    return render(request, 'book/book.html', context)

def chapter(request, chapter_id):
    '''章节里面内容'''
    chapter = Chapter.objects.get(id=chapter_id)
    book = chapter.book
    topics = chapter.topic_set.order_by('id')
    context = {'chapter': chapter, 'topics':topics, 'book': book}
    return render(request, 'book/chapter.html', context)

def topic(request, topic_id):
    '''讨论话题的全部内容'''
    topic = Topic.objects.get(id=topic_id)
    chapter = topic.chapter
    entries = topic.entry_set.order_by('id')
    context = {'topic': topic, 'entries': entries, 'chapter': chapter}
    return render(request, 'book/topic.html', context)

def new_topic(request, chapter_id):
    '''在指定章节下面生成新的话题'''
    #指定章节
    chapter = Chapter.objects.get(id=chapter_id)

    if request.method != 'POST':
        #没有提交数据，创建一个新的表单
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            #新问题保存在new_topic中，而不保存在数据库中
            new_topic = form.save(commit=False)
            #指定多对一属性
            new_topic.chapter = chapter
            #然后再保存
            new_topic.save()

            #重定向到章节的所有的问题页面
            return HttpResponseRedirect(reverse('book:chapter', args=[chapter_id]))

    context = {'form': form, 'chapter': chapter}
    return render(request, 'book/new_topic.html', context)

book/templates/book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
</head>
<body>
    <p>
    <a href="{% url 'book:index' %}"> 首页 </a> -
    <a href="{% url 'book:books' %}"> 书目 </a>
{#    {% if user.is_authenticated %}#}
{#        Hello,{{user.username}}.#}
{#        <a href="{% url 'users:logout' %}"> Log out</a>#}
{#    {% else %}#}
{#        <a href="{% url 'users:register' %}"> register </a> -#}
{#        <a href="{% url 'users:login' %}"> Log in </a>#}
{#    {% endif %}#}
    </p>
    {% block content %}{% endblock content%}
</body>
</html>

book/templates/book/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>book</title>
</head>
<body>
    {% extends "book/base.html" %}
    {% block content %}
    <p>
        Book: {{ book.name }}
    </p>
    <ul>
    {% for chapter in chapters %}
        <li>
            <a href="{% url 'book:chapter' chapter.id %}">{{ chapter.name }}</a>
        </li>
    {% empty %}
        <li>暂时没有章节</li>
    {% endfor %}
    </ul>
    {% endblock content%}
</body>
</html>

book/templates/book/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>books</title>
</head>
<body>
    {% extends "book/base.html" %}
    {% block content %}
    <p>
        Books
    </p>
    <ul>
    {% for book in books %}
        <li>
            <a href="{% url 'book:book' book.id %}">{{ book }}</a>
        </li>
    {% empty %}
        <li>暂时没有书目</li>
    {% endfor %}
    </ul>
{#    <ul>#}
{#        {% for book in books %}#}
{#            <li>#}
{#                <a href="{% url 'book:' topic.id%}"> {{topic}}</a>#}
{#            </li>#}
{#        {% empty %}#}
{#            <li>#}
{#                No topics#}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#    <a href="{% url 'Notebook:new_topic' %}"> add a new topic </a>#}

    {% endblock content%}
</body>
</html>

book/templates/book/chapter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>chapter</title>
</head>
<body>
    {% extends "book/base.html" %}
    {% block content %}
    <p><a href="{% url 'book:book' book.id %}">回到目录</a></p>
    <p>
        Chapter: {{ chapter.name }}
    </p>
    <ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'book:topic' topic.id %}">{{ topic.topic }}</a>
        </li>
    {% empty %}
        <li>暂时没有内容</li>
    {% endfor %}

    </ul>
    <a href="{% url 'book:new_topic' chapter.id%}">提问/感想</a>
    {% endblock content%}
</body>
</html>

book/templates/book/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
{% extends 'book/base.html' %}
{% block content %}
主页

python
微积分
线性代数
......
{% endblock content %}
</body>
</html>

book/templates/book/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new_topic</title>
</head>
<body>
{% extends "book/base.html" %}
{% block content %}
    <p>
        <a href="{% url 'book:chapter' chapter.id %}">回到本章</a>
    </p>
    <p>提问/感想：</p>
    <form action="{% url 'book:new_topic' chapter.id%}" method="post">
        {% csrf_token %}
        {#以段落方式渲染#}
        {{ form.as_p }}
        <button name="submit">提交</button>
    </form>
{% endblock content %}
</body>
</html>

book/templates/book/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>entry</title>
</head>
<body>
    {% extends "book/base.html" %}
    {% block content %}
    <p><a href="{% url 'book:chapter' chapter.id %}">回到本章</a></p>
    <p>
        Topic: {{ topic.topic }}
    </p>
    <ul>
    {% for entry in entries %}
        <li>{{ entry.entry }}</li>
    {% empty %}
        <li>暂时没有内容</li>
    {% endfor %}
    </ul>
    {% endblock content%}
</body>
</html>